<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iHxmihA' shared service.

return $this->privates['.service_locator.iHxmihA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ControllerAluno::sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerProfessor::sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerProjeto::sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerRelevancia::sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerSugestao::sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerVisitante::sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerAluno:sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerProfessor:sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerProjeto:sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerRelevancia:sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerSugestao:sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\ControllerVisitante:sendEmail' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
], [
    'App\\Controller\\ControllerAluno::sendEmail' => '?',
    'App\\Controller\\ControllerProfessor::sendEmail' => '?',
    'App\\Controller\\ControllerProjeto::sendEmail' => '?',
    'App\\Controller\\ControllerRelevancia::sendEmail' => '?',
    'App\\Controller\\ControllerSugestao::sendEmail' => '?',
    'App\\Controller\\ControllerVisitante::sendEmail' => '?',
    'App\\Controller\\ControllerAluno:sendEmail' => '?',
    'App\\Controller\\ControllerProfessor:sendEmail' => '?',
    'App\\Controller\\ControllerProjeto:sendEmail' => '?',
    'App\\Controller\\ControllerRelevancia:sendEmail' => '?',
    'App\\Controller\\ControllerSugestao:sendEmail' => '?',
    'App\\Controller\\ControllerVisitante:sendEmail' => '?',
]);
