<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1gHWyCq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1gHWyCq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1gHWyCq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1gHWyCq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1gHWyCq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1gHWyCq',
    'container.build_id' => 'aac0bc6b',
    'container.build_time' => 1573579294,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1gHWyCq');
