<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'test' => [[], ['_controller' => 'App\\Controller\\ControllerLoginController::test'], [], [['text', '/test']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\ControllerLoginController::index'], [], [['text', '/login']], [], []],
    'send' => [[], ['_controller' => 'App\\Controller\\ControllerVisitante::sendEmail'], [], [['text', '/send']], [], []],
    'create_aluno' => [[], ['_controller' => 'App\\Controller\\ControllerAluno::createAluno'], [], [['text', '/alunos']], [], []],
    'update_aluno' => [['id'], ['_controller' => 'App\\Controller\\ControllerAluno::updateAluno'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/alunos']], [], []],
    'list_alunos' => [[], ['_controller' => 'App\\Controller\\ControllerAluno::search'], [], [['text', '/alunos']], [], []],
    'create_professor' => [[], ['_controller' => 'App\\Controller\\ControllerProfessor::createProfessor'], [], [['text', '/professor']], [], []],
    'list_professor' => [[], ['_controller' => 'App\\Controller\\ControllerProfessor::search'], [], [['text', '/professor']], [], []],
    'update_professor' => [['id'], ['_controller' => 'App\\Controller\\ControllerProfessor::updateProfessor'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/professor']], [], []],
    'create_projeto' => [[], ['_controller' => 'App\\Controller\\ControllerProjeto::create'], [], [['text', '/projeto']], [], []],
    'update_projeto' => [['projetoId'], ['_controller' => 'App\\Controller\\ControllerProjeto::updateProjeto'], [], [['variable', '/', '[^/]++', 'projetoId', true], ['text', '/projeto']], [], []],
    'list_projeto' => [[], ['_controller' => 'App\\Controller\\ControllerProjeto::search'], [], [['text', '/projeto']], [], []],
    'vincularAlunoProjeto' => [['id'], ['_controller' => 'App\\Controller\\ControllerProjeto::vincularAlunoEntity'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/projeto/vincular']], [], []],
    'desvincularAlunoProjeto' => [['id_projeto'], ['_controller' => 'App\\Controller\\ControllerProjeto::desvincularAluno'], [], [['variable', '/', '[^/]++', 'id_projeto', true], ['text', '/projeto/desvincular']], [], []],
    'detail_projeto' => [['id'], ['_controller' => 'App\\Controller\\ControllerProjeto::detalheProjeto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/projeto']], [], []],
    'filter_projeto' => [['texto'], ['_controller' => 'App\\Controller\\ControllerProjeto::pesquisarProjeto'], [], [['variable', '/', '[^/]++', 'texto', true], ['text', '/projetoFiltro']], [], []],
    'removeProjeto' => [['id'], ['_controller' => 'App\\Controller\\ControllerProjeto::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/projeto']], [], []],
    'create_visitante' => [[], ['_controller' => 'App\\Controller\\ControllerVisitante::create'], [], [['text', '/visitantes']], [], []],
    'adicionar_sugestao' => [[], ['_controller' => 'App\\Controller\\ControllerSugestao::create'], [], [['text', '/sugestao']], [], []],
    'detalhe_sugestao' => [[], ['_controller' => 'App\\Controller\\ControllerSugestao::search'], [], [['text', '/sugestao']], [], []],
    'lista_visitantes' => [[], ['_controller' => 'App\\Controller\\ControllerVisitante::search'], [], [['text', '/visitantes']], [], []],
    'remove_visitante' => [['id'], ['_controller' => 'App\\Controller\\ControllerVisitante::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/visitante']], [], []],
    'create_user' => [[], ['_controller' => 'App\\Controller\\ControllerVisitante::create'], [], [['text', '/visitante']], [], []],
];
