<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ControllerRelevancia' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\GenericController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\ControllerRelevancia.php';
include_once $this->targetDirs[3].'\\src\\Helper\\EntityFactory.php';
include_once $this->targetDirs[3].'\\src\\Helper\\RelevanciaFactory.php';

$this->services['App\\Controller\\ControllerRelevancia'] = $instance = new \App\Controller\ControllerRelevancia(($this->privates['App\\Repository\\RelevanciaRepository'] ?? $this->load('getRelevanciaRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), new \App\Helper\RelevanciaFactory());

$instance->setContainer(($this->privates['.service_locator.CDOTD6.'] ?? $this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\Controller\\ControllerRelevancia', $this));

return $instance;
